# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ValidateCsv < Formula
  desc "CLI tool to validate CSV by duplicates and sums of rows."
  homepage "https://github.com/robinlieb/validate-csv"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.3.0/validate-csv_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "7355a50a7d702df045f0662fbe14971a5e3433044cb071e0a479157cab851e20"

      def install
        bin.install "validate-csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.3.0/validate-csv_1.3.0_Darwin_arm64.tar.gz"
      sha256 "77a89726ddf03aa6062aa80c621397f0511c4dc322eecc8a19588a0693c183b3"

      def install
        bin.install "validate-csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.3.0/validate-csv_1.3.0_Linux_x86_64.tar.gz"
      sha256 "2e71fd49b71b8f38a85eca43906c375a11298597137d058cf5c60c9823c1207d"

      def install
        bin.install "validate-csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.3.0/validate-csv_1.3.0_Linux_arm64.tar.gz"
      sha256 "a118bdb92a9d820e9fbe60207ecebe7d86088ecba988f5dc7955e9a9e738ebe2"

      def install
        bin.install "validate-csv"
      end
    end
  end
end
