# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ValidateCsv < Formula
  desc "CLI tool to validate CSV by duplicates and sums of rows."
  homepage "https://github.com/robinlieb/validate-csv"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.4.0/validate-csv_1.4.0_Darwin_x86_64.tar.gz"
      sha256 "4474c1da26cef1f52faa5fdf475d9085d4204caa7234bca1e2ff0229a0915eb7"

      def install
        bin.install "validate-csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.4.0/validate-csv_1.4.0_Darwin_arm64.tar.gz"
      sha256 "943250561b103104406d6c2d6a5baecb4f8582def0ecd30eb5bb23020b917ffa"

      def install
        bin.install "validate-csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.4.0/validate-csv_1.4.0_Linux_x86_64.tar.gz"
      sha256 "07edba02c14beffdb69bc29743d0511ea7f64b6aa9fce4eb851f36322931316f"

      def install
        bin.install "validate-csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinlieb/validate-csv/releases/download/v1.4.0/validate-csv_1.4.0_Linux_arm64.tar.gz"
      sha256 "7e6c7aba08a04c12e028839ee7ed17315197a903367431b0a112033e779e542c"

      def install
        bin.install "validate-csv"
      end
    end
  end
end
